apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-platform.fullname" . }}-admin
  labels:
    {{- include "api-platform.labelsADMIN" . | nindent 4 }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "api-platform.selectorLabelsADMIN" . | nindent 4 }}
